name: ${project.name}
main: com.github.ucchyocean.ct.ColorTeaming
version: ${project.version}
authors: [ucchy,owatakun]
description: ${project.description}
website: 'http://forum.minecraftuser.jp/viewtopic.php?f=38&t=9729'
depend: []
softdepend: [Vault,AttributesAPI]
api-version: 1.13
commands:
  colorteaming:
    description: ColorTeamingの管理用コマンド
    aliases: ct
    usage: |
           /<command> reload - ColorMeTeaming の config.yml を再読み込みします。
           /<command> add (team) (player) - playerをteamに追加します。
           /<command> add (team) all - プレイヤー全員をteamに追加します。
           /<command> add (team) rest - チーム未設定プレイヤー全員をteamに追加します。
           /<command> leave (player) - playerがチームに所属している場合、チームから離脱させます。
           /<command> remove (team) - teamを解散します。
           /<command> removeAll - 全てのチームを解散します。
           /<command> trophy (amount) - キル数達成時の通知を設定します。
           /<command> reachTrophy (amount) - キル数リーチ時の通知を設定します。
           /<command> allowJoinRandom (on|off) - /cjoin コマンドの利用許可をオンオフします。
           /<command> allowJoinAny (on|off) - /cjoin (group) コマンドの利用許可をオンオフします。
           /<command> allowLeave (on|off) - /cleave コマンドの利用許可をオンオフします。
           /<command> side (kill|death|point|rest) - サイドバーのスコア表示を変更します。
           /<command> side clear - サイドバーのスコア表示を消去します。
           /<command> list (kill|death|point|health) - TABキーリストのスコア表示を変更します。
           /<command> list clear - TABキーリストのスコア表示を消去します。
           /<command> below (kill|death|point|health) - 名前下のスコア表示を変更します。
           /<command> below clear - 名前下のスコア表示を消去します。
    permission: colorteaming.team
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorrandom:
    description: 新しいチーム分けをランダムに設定するためのコマンド
    aliases: [crandom,randomcolor,rc]
    usage: |
           /<command> - 全てのプレイヤーを2チームにチーム分けします。
           /<command> (numberOfTeams) - 全てのプレイヤーを、numberOfTeamsの数のチームにチーム分けします。
           /<command> rest - 色が設定されていない人を、現在設定されているチームにランダム割り振りします。
    permission: colorteaming.random
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorcount:
    description: メンバーを一覧表示するコマンド
    aliases: cc
    usage: |
           /<command> - 各色チームのメンバーを一覧表示します。
           /<command> all - 全てのプレイヤーのメンバーを一覧表示します。
           /<command> say [all] - 各色チームのメンバーの一覧を、サーバー全体メッセージで表示します。
    permission: colorteaming.count
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorfriendlyfire:
    description: メンバー間の攻撃の有効無効を切り替えるコマンド
    aliases: cff
    usage: |
           /<command> (on|off) - 各色チームのメンバー間の攻撃を、onで有効に、offで無効に設定します。
           /<command> invisible (on|off) - 各色チームの透明なメンバーを、onで見えるように、offで見えないようにします。
    permission: colorteaming.friendlyfire
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorchat:
    description: チームチャットの有効無効を切り替えるコマンド
    aliases: cchat
    usage: |
           /<command> (on|off) - 各色チームのメンバーのチャットを、onでチームチャットに、offで通常チャットに設定します。
           /<command> (opon|opoff) - 各チームのチームチャットを、OPが傍聴するかどうかを設定します。
           /<command> (logon|logoff) - 各チームのチームチャットを、server.logに記録します。
           /<command> (team) (message) - 指定したチームにメッセージを送ります。
    permission: colorteaming.chat
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorleader:
    description: 各チームから大将を選出するコマンド
    aliases: cl
    usage: |
           /<command> (team) (player) - playerを、teamの大将に設定します。
           /<command> (team) random [(numberOfLeaders)] - teamの中からランダムに1人を、teamの大将に設定します。numberOfLeadersを指定した場合、指定した人数を大将として選出します。
           /<command> all [(numberOfLeaders)] - 全てのチームからランダムに1人を、各チームの大将に設定します。numberOfLeadersを指定した場合、指定した人数を各チームから大将として選出します。
           /<command> clear - 大将設定を削除します。
           /<command> view - 大将設定を表示します。
           /<command> say - 大将設定を、サーバー全体メッセージで表示します。
    permission: colorteaming.leader
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colortp:
    description: 各チームをテレポートするためのコマンド
    aliases: ctp
    usage: |
           /<command> (team|player) [(world)] (x) (y) (z) - teamのメンバー全員、または指定したプレイヤーを、(world):(x),(y),(z) の場所にテレポートします。
           /<command> (team|player) here - teamのメンバー全員、または指定したプレイヤーを、コマンドを実行した人の場所にテレポートします。
           /<command> (team|player) spawn - teamのメンバー全員、または指定したプレイヤーを、チームのリスポーンポイントにテレポートします。
           /<command> (team|player) (point) - teamのメンバー全員、または指定したプレイヤーを、指定されたポイントにテレポートします。
           /<command> set (point) [(world)] (x) (y) (z) - (world):(x),(y),(z) の場所に、新しいポイントを登録します。
           /<command> set (point) here - コマンドを実行した人の場所に、新しいポイントを登録します。
           /<command> remove (point) - 登録されたポイントを削除します。
           /<command> all spawn - 全てのプレイヤーを、チームのリスポーンポイントにテレポートします。
           /<command> all (point) - 全てのプレイヤーを、指定されたポイントにテレポートします。
           /<command> list - 登録されたポイントを一覧表示します。
    permission: colorteaming.tp
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorclass:
    description: インベントリを設定されたアイテムで初期化するためのコマンド
    aliases: cclass
    usage: |
           /<command> check - 手に持っているアイテムの情報を表示します。
           /<command> (team) (class) - teamのメンバー全員のアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
           /<command> (player) (class) - player のアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
           /<command> all (class) - 全プレイヤーのアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
           /<command> export (class) - 実行したプレイヤーの現在の状態を、指定したクラス名でクラス設定を作成して保存します。
    permission: colorteaming.class
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorpoint:
    description: チームごとのキルデス数を表示するためのコマンド
    aliases: [ckill,ck,cpoint,cp]
    usage: |
           /<command> - 全てのチームごとのキルデス数カウントを参照します。
           /<command> say - 全てのチームごとのキルデス数カウントを、サーバー全体メッセージで表示します。
           /<command> clear - 全てのチームごとのキルデス数カウントを初期化して0にします。
           /<command> set (team|player) (point) - teamまたはplayerのポイントを、pointに設定します。
           /<command> add (team|player) (point) - teamまたはplayerのポイントを、pointのぶん追加します。マイナス指定で減らします。
    permission: colorteaming.point
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorspawn:
    description: チームごとのリスポーンポイントを設定するためのコマンド
    aliases: [cspawn,cs]
    usage: |
           /<command> (team) - teamのメンバーのリスポーンポイントを、コマンドを実行した人の場所に設定します。
           /<command> (team) (MapName) - マップMapNameにおけるteamのメンバーのリスポーンポイントを、コマンドを実行した人の場所に設定します。
           /<command> (team) (x) (y) (z) - teamのメンバー全員のリスポーンポイントを、(x),(y),(z) の場所に設定します。
           /<command> switch (MapName) - リスポーンポイントの設定を、MapNameに変更します。
           /<command> switch random - リスポーンポイントの設定を、登録されているマップ名からランダムに選択して変更します。
           /<command> switch - リスポーンポイントの設定を、デフォルトに戻します。
           /<command> remove (team) - teamのリスポーンポイント設定を削除します。
           /<command> remove all - 全てのチームのリスポーン設定を削除します。
           /<command> world - ワールドのリスポーンポイントを設定します。
           /<command> list - リスポーン設定を一覧表示します。
    permission: colorteaming.spawn
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorremove:
    description: チームを離脱する条件を設定するためのコマンド
    aliases: cr
    usage: |
           /<command> death (on|off) - 死亡時に自動でチームから抜けるかどうかを設定します。
           /<command> quit (on|off) - ログアウト時に自動でチームから抜けるかどうかを設定します。
           /<command> changeworld (on|off) - ワールド変更時に自動でチームから抜けるかどうかを設定します。
    permission: colorteaming.remove
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorexplode:
    description: チームを爆発させるコマンド（爆発オチ用）
    aliases: [ce,cexplode]
    usage: |
           /<command> (team) - teamのメンバー全員が爆発して死亡します。
           /<command> (player) - playerが爆発して死亡します。
           /<command> all - 全プレイヤーが爆発して死亡します。
    permission: colorteaming.explode
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorgive:
    description: チームメンバーのインベントリに、アイテムを追加するコマンド
    aliases: cgive
    usage: |
           /<command> (team) (item[:amount]) - 指定したアイテムを、teamのメンバー全員に配布します。実行例「/<command> red BREAD:64」
           /<command> (player) (item[:amount]) - 指定したアイテムを、playerに配布します。
           /<command> (team) hand - 手に持ったアイテムを、teamのメンバー全員に配布します。
           /<command> (player) hand - 手に持ったアイテムを、playerに配布します。
    permission: colorteaming.give
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colornametag:
    description: ネームタグの表示非表示を切り替えるコマンド
    aliases: [cn,cnametag]
    usage: |
           /<command> on - ネームタグを表示に設定します。
           /<command> off - ネームタグを非表示に設定します。
           /<command> team - ネームタグを他チームから非表示に設定します。
           /<command> other - ネームタグを自チームから非表示に設定します。
    permission: colorteaming.nametag
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  coloroption:
    description: チームのオプション設定を切り替えるコマンド
    aliases: [coption]
    usage: |
           /<command> nametag (on|off|team|other) - ネームタグの表示非表示を切り替えます。
           /<command> collision (on|off|team|other) - プレイヤー間の当たり判定の有り無しを切り替えます。
           /<command> deathmessage (on|off|team|other) - 死亡メッセージの表示非表示を切り替えます。
    permission: colorteaming.option
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorglobal:
    description: チームチャット有効時にグローバルへ発言するためのコマンド
    aliases: [cg,g]
    usage: /<command> (message) - チームチャットが設定されている状態で、通常のチャット発言を行います。
    permission: colorteaming-user.global
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorjoin:
    description: 一般プレイヤーが、任意のチームへ参加するためのコマンド
    aliases: cjoin
    usage: |
           /<command> (team) - teamに参加します。設定で allowPlayerJoinAny が true でないと使用できません。
           /<command> - 人数が少ないチームへ参加します。設定で allowPlayerJoinRandom が true でないと使用できません。
           /<command> random - /<command> と同様です。
    permission: colorteaming-user.join
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorleave:
    description: 一般プレイヤーが、チームから離脱するためのコマンド
    aliases: cleave
    usage: /<command> - チームから離脱します。設定で allowPlayerLeave が true でないと使用できません。
    permission: colorteaming-user.leave
    permission-message: パーミッション "<permission>" が無いため、実行できません。
permissions:
  colorteaming.team:
    description: colorteaming(ct)コマンドの使用権限
    default: op
  colorteaming.random:
    description: colorrandom(crandom)コマンドの使用権限
    default: op
  colorteaming.count:
    description: colorcount(cc)コマンドの使用権限
    default: op
  colorteaming.friendlyfire:
    description: colorfriendlyfire(cff)コマンドの使用権限
    default: op
  colorteaming.chat:
    description: colorchat(cchat)コマンドの使用権限
    default: op
  colorteaming.leader:
    description: colorleader(cl)コマンドの使用権限
    default: op
  colorteaming.tp:
    description: colortp(ctp)コマンドの使用権限
    default: op
  colorteaming.class:
    description: colorclass(cclass)コマンドの使用権限
    default: op
  colorteaming.point:
    description: colorkill(ckill)コマンドの使用権限
    default: op
  colorteaming.spawn:
    description: colorspawn(cspawn)コマンドの使用権限
    default: op
  colorteaming.remove:
    description: colorremove(cr)コマンドの使用権限
    default: op
  colorteaming.explode:
    description: colorexplode(cexplode)コマンドの使用権限
    default: op
  colorteaming.give:
    description: colorgive(cgive)コマンドの使用権限
    default: op
  colorteaming.nametag:
    description: colornametag(cn)コマンドの使用権限
    default: op
  colorteaming.option:
    description: coloroption(coption)コマンドの使用権限
    default: op
  colorteaming.*:
    children:
      colorteaming.team: true
      colorteaming.random: true
      colorteaming.count: true
      colorteaming.friendlyfire: true
      colorteaming.chat: true
      colorteaming.leader: true
      colorteaming.tp: true
      colorteaming.class: true
      colorteaming.kill: true
      colorteaming.spawn: true
      colorteaming.remove: true
      colorteaming.explode: true
      colorteaming.give: true
      colorteaming.nametag: true
      colorteaming.option: true
    description: ColorTeamingプラグインの管理系コマンド全ての使用権限
  colorteaming-user.global:
    description: colorglobal(g)コマンドの使用権限
    default: true
  colorteaming-user.join:
    description: colorjoin(cjoin)コマンドの使用権限
    default: true
  colorteaming-user.leave:
    description: colorleave(cleave)コマンドの使用権限
    default: true
  colorteaming-user.*:
    children:
      colorteaming-user.global: true
      colorteaming-user.join: true
      colorteaming-user.leave: true
    description: ColorTeamingプラグインのユーザー系コマンド全ての使用権限


